shared:
  ingress_domain: "tap-ui.com"
  image_registry:
    project_path: "314525640319.dkr.ecr.us-east-1.amazonaws.com/tap-images"

ceip_policy_disclosed: true

#The above keys are minimum numbers of entries needed in tap-values.yaml to get a functioning TAP Full profile installation.

#Below are the keys which may have default values set, but can be overridden.

profile: full # Can take iterate, build, run, view.

excluded_packages:
- policy.apps.tanzu.vmware.com

supply_chain: basic # Can take testing, testing_scanning.

ootb_supply_chain_basic: # Based on supply_chain set above, can be changed to ootb_supply_chain_testing, ootb_supply_chain_testing_scanning.
  registry:
    server: 314525640319.dkr.ecr.us-east-1.amazonaws.com
    # The prefix of the ECR repository.  Workloads will need
    # two repositories created:
    #
    # tanzu-application-platform/<workloadname>-<namespace>
    # tanzu-application-platform/<workloadname>-<namespace>-bundle
    repository: tanzu-application-platform

contour:
  infrastructure_provider: aws
  envoy:
    service:
      aws:
        LBType: nlb
        
buildservice:
  kp_default_repository: 314525640319.dkr.ecr.us-east-1.amazonaws.com/tanzu-application-platform
    # kp_default_repository: 314525640319.dkr.ecr.us-east-1.amazonaws.com/tap-build-service
    #Enable the build service k8s service account to bind to the AWS IAM Role
  kp_default_repository_aws_iam_role_arn: "arn:aws:iam::314525640319:role/tap-build-service"
  exclude_dependencies: true

ootb_templates:
  # Enable the config writer service to use cloud based iaas authentication
  # which are retrieved from the developer namespace service account by
  # default
  iaas_auth: true

tap_gui:
  service_type: ClusterIP
  app_config:
    catalog:
      locations:
        - type: url
          target: https://github.com/TalMalchi/tap-gui-catalog/blob/main/catalog-info.yaml
    backend:
      baseUrl: https://tap-gui.tap-ui.com
      cors:
        origin: https://tap-gui.tap-ui.com
    app:
      baseUrl: https://tap-gui.tap-ui.com
    integrations:
      github: # Other integrations available see NOTE below
        - host: github.com
          token: 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
    auth:
      environment: development
      providers:
        github:
          development:
            clientId: affbe0f335ddf5721f78
            clientSecret: 9c681e09b86b75ef18271ec4c8c0b20f69d38f83
              
metadata_store:
  ns_for_export_app_cert: "*"
  app_service_type: ClusterIP # Defaults to LoadBalancer. If shared.ingress_domain is set earlier, this must be set to ClusterIP.

scanning:
  metadataStore:
    url: "" # Configuration is moved, so set this string to empty.
