apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-app
    apps.tanzu.vmware.com/has-tests: false
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/metric: "rps"
      autoscaling.knative.dev/target: "5"
      autoscaling.knative.dev/window: "10s"
      autoscaling.knative.dev/max-scale: "5"
      autoscaling.knative.dev/min-scale: "1"
  build:
    env:
      - name: BP_JVM_VERSION
        value: 17
  source:
    git:
      ref:
        branch: main
      url: https://github.com/dor-bynet/tanzu-java-web-app.git
